/**
 * Permission catalogue. Must match the rows seeded by `drizzle/0001_m1_security.sql`
 * (verified by tests/migrations.test.ts). Permissions are technical capabilities, not
 * Bureau approval authorities.
 */
export const PERMISSIONS = {
  READ_STOCK: 'READ_STOCK',
  READ_LEDGER: 'READ_LEDGER',
  READ_AUDIT: 'READ_AUDIT',
  READ_WAREHOUSES: 'READ_WAREHOUSES',
  READ_ITEMS: 'READ_ITEMS',
  READ_POLICIES: 'READ_POLICIES',
  READ_USERS: 'READ_USERS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_USER_ROLES: 'MANAGE_USER_ROLES',
  MANAGE_WAREHOUSE_ACCESS: 'MANAGE_WAREHOUSE_ACCESS',
  MANAGE_ITEMS: 'MANAGE_ITEMS',
  MANAGE_MASTER_REFERENCE: 'MANAGE_MASTER_REFERENCE',
  READ_OPENING_BALANCE: 'READ_OPENING_BALANCE',
  PREPARE_OPENING_BALANCE: 'PREPARE_OPENING_BALANCE',
  APPROVE_OPENING_BALANCE: 'APPROVE_OPENING_BALANCE',
  POST_OPENING_BALANCE: 'POST_OPENING_BALANCE',
  READ_RECEIPTS: 'READ_RECEIPTS',
  PREPARE_RECEIPTS: 'PREPARE_RECEIPTS',
  RECEIVE_RECEIPTS: 'RECEIVE_RECEIPTS',
  INSPECT_RECEIPTS: 'INSPECT_RECEIPTS',
  RETURN_REJECTED_STOCK: 'RETURN_REJECTED_STOCK',
  READ_REQUISITIONS: 'READ_REQUISITIONS',
  PREPARE_REQUISITIONS: 'PREPARE_REQUISITIONS',
  APPROVE_REQUISITIONS: 'APPROVE_REQUISITIONS',
  READ_ISSUES: 'READ_ISSUES',
  PREPARE_ISSUES: 'PREPARE_ISSUES',
  POST_ISSUES: 'POST_ISSUES',
  READ_TRANSFERS: 'READ_TRANSFERS',
  PREPARE_TRANSFERS: 'PREPARE_TRANSFERS',
  APPROVE_TRANSFERS: 'APPROVE_TRANSFERS',
  DISPATCH_TRANSFERS: 'DISPATCH_TRANSFERS',
  RECEIVE_TRANSFERS: 'RECEIVE_TRANSFERS',
  WAREHOUSE_SCOPE_ALL: 'WAREHOUSE_SCOPE_ALL',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
